### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by DarkAndBlue** [DarkAndBlue/KeepThatMusic#1]
All sounds are getting muted and this exception spams inside the console
```
[19:49:40] [Sound engine/ERROR]: Error executing task on Sound executor
java.lang.IllegalStateException: Tried to release unknown channel
	at net.minecraft.class_4225.method_19662(class_4225.java:301) ~[client-intermediary.jar:?]
	at net.minecraft.class_4235$class_4236.method_19736(class_4235.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_4235.method_19731(class_4235.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_4238.method_19765(class_4238.java:42) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by DarkAndBlue** [comment]
```
[20:47:54] [Sound engine/ERROR]: Error executing task on Sound executor
java.lang.IllegalStateException: Tried to release unknown channel
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at net.minecraft.client.sound.SoundEngine.release(SoundEngine:301) ~[?:?]
	at net.minecraft.client.sound.Channel$SourceManager.close(Channel:42) ~[?:?]
	at net.minecraft.client.sound.Channel.method_19731(Channel:84) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.sound.SoundExecutor.waitForStop(SoundExecutor:42) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by DarkAndBlue** [comment]
The issue seems to be fixed
